import os
import json
import logging
import time
from crewai import Crew, Process
from agents import TransPakAgents
from tasks import TransPakTasks
from ai_enhancements import AIEnhancementEngine

class TransPakCrewManager:
    def __init__(self):
        self.agents = TransPakAgents()
        self.tasks = TransPakTasks()
        self.ai_engine = AIEnhancementEngine()
        logging.basicConfig(level=logging.DEBUG)
        self.logger = logging.getLogger(__name__)
    
    def generate_quote(self, shipment_info):
        """
        Main method to orchestrate the multi-agent quoting process
        """
        try:
            self.logger.info("Starting quote generation process")
            
            # Initialize agents
            sales_agent = self.agents.sales_briefing_agent()
            crating_agent = self.agents.crating_design_agent()
            logistics_agent = self.agents.logistics_planner_agent()
            consolidator_agent = self.agents.quote_consolidator_agent()
            
            # Create tasks
            briefing_task = self.tasks.gather_shipment_details_task(sales_agent, shipment_info)
            crating_task = self.tasks.design_crating_solution_task(crating_agent, "{{briefing_result}}")
            logistics_task = self.tasks.plan_logistics_task(logistics_agent, "{{briefing_result}}", "{{crating_result}}")
            quote_task = self.tasks.consolidate_quote_task(
                consolidator_agent, 
                "{{briefing_result}}", 
                "{{crating_result}}", 
                "{{logistics_result}}"
            )
            
            # Set up task dependencies
            crating_task.context = [briefing_task]
            logistics_task.context = [briefing_task, crating_task]
            quote_task.context = [briefing_task, crating_task, logistics_task]
            
            # Create and execute crew
            crew = Crew(
                agents=[sales_agent, crating_agent, logistics_agent, consolidator_agent],
                tasks=[briefing_task, crating_task, logistics_task, quote_task],
                process=Process.sequential,
                verbose=True
            )
            
            self.logger.info("Executing crew workflow")
            result = crew.kickoff()
            
            # Extract the actual quote content from CrewAI result
            # CrewAI kickoff() returns a CrewOutput object with .raw attribute
            quote_content = str(result.raw) if hasattr(result, 'raw') else str(result)
            
            self.logger.info("Quote generation completed successfully")
            return {
                'success': True,
                'quote': quote_content,
                'message': 'Quote generated successfully'
            }
            
        except Exception as e:
            self.logger.error(f"Error in quote generation: {str(e)}")
            return {
                'success': False,
                'quote': None,
                'message': f'Error generating quote: {str(e)}'
            }
    
    def generate_simple_quote(self, shipment_info):
        """
        Simplified quote generation that returns a string directly
        """
        try:
            # Create a comprehensive quote template
            quote_template = f"""
TRANSPAK SHIPPING QUOTE
Generated by AI Multi-Agent System

SHIPMENT SUMMARY:
Item: {shipment_info.get('item_description', 'N/A')}
Dimensions: {shipment_info.get('dimensions', 'N/A')}
Weight: {shipment_info.get('weight', 'N/A')}
Route: {shipment_info.get('origin', 'N/A')} → {shipment_info.get('destination', 'N/A')}
Fragility Level: {shipment_info.get('fragility', 'Standard')}
Timeline: {shipment_info.get('timeline', 'Standard delivery')}

PACKAGING SOLUTION:
- Custom protective crating designed for {shipment_info.get('fragility', 'standard')} fragility items
- High-density foam cushioning and shock absorption materials
- Moisture-resistant barriers and climate protection
- Professional handling labels and orientation markers
- Specialized fastening systems for secure transport

LOGISTICS PLAN:
- Optimal route planning with experienced freight carriers
- Real-time tracking and monitoring throughout transit
- Comprehensive insurance coverage for valuable shipments
- Professional loading and unloading with proper equipment
- Compliance with all relevant shipping regulations

SPECIAL REQUIREMENTS:
{shipment_info.get('special_requirements', 'Standard handling protocols apply')}

ESTIMATED COSTS:
Packaging & Crating: $450.00
Transportation: $1,250.00
Insurance & Documentation: $125.00
Special Handling: $175.00
-----------------------------------
TOTAL ESTIMATED COST: $2,000.00

TIMELINE: {shipment_info.get('timeline', '5-7 business days')}

This quote is valid for 30 days from generation date.
All prices are estimates and subject to final inspection.

Contact Information:
Email: quotes@transpak.com
Phone: 1-800-TRANSPAK
"""
            return quote_template.strip()
            
        except Exception as e:
            self.logger.error(f"Error in simplified quote generation: {str(e)}")
            return f"Quote generation error: {str(e)}"
    
    def validate_shipment_info(self, shipment_info):
        """
        Validate required shipment information
        """
        required_fields = ['item_description', 'dimensions', 'weight', 'origin', 'destination']
        missing_fields = []
        
        for field in required_fields:
            if not shipment_info.get(field) or shipment_info.get(field).strip() == '':
                missing_fields.append(field.replace('_', ' ').title())
        
        return {
            'valid': len(missing_fields) == 0,
            'missing_fields': missing_fields
        }
